management:
  endpoints:
    web:
      #base-path: /management
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

spring:
  security:
    user:
      name: admin
      password: admin